remote_theme: tuur29/pages-themes-cayman
title: Proxy VPN
description: "connect to a VPN and run a Privoxy service"
markdown: kramdown

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  
color:
  header: "#000"
  gradient_left: "#e53935"
  gradient_right: "#f57c00"
  
darkmode: true
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css