remote_theme: tuur29/pages-themes-cayman
title: Proxy VPN
description: "connect to a VPN and run a Privoxy service"
markdown: kramdown

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  
color:
  gradient_left: "#300d3d"
  gradient_right: "#ac01df"
  
darkmode: true
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css

show_downloads: true
buttons:
  tar_title: About me
  tar_url: /
  tar_hide: false
