remote_theme: tuur29/pages-themes-cayman
title: Proxy VPN
description: "run a Privoxy service over VPN to provide a privacy-enhanced web proxy"
markdown: kramdown
url: https://code.sitton.dev
baseurl: /ProxyVPN

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  
color:
  gradient_left: "#300d3d"
  gradient_right: "#ac01df"
  
darkmode: true
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css

show_downloads: true
buttons:
  zip_hide: true
  tar_title: About me
  tar_url: /
  tar_hide: false
